spring.application.name=matching-service
server.port=8083
spring.profiles.active=reactive

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

market.open=10:00
market.close=22:00

spring.cloud.function.definition=handleMatch
logging.level.org.springframework.cloud.stream.function=WARN
#
spring.cloud.stream.bindings.handleMatch-in-0.destination=match.commands
#spring.cloud.stream.bindings.handleMatch-in-0.group=matching-engine-queue
#spring.cloud.stream.bindings.handleMatch-in-0.content-type=application/json
#
#spring.cloud.stream.bindings.handleMatch-out-0.destination=
#
spring.cloud.stream.dynamicDestinations=order.events,trade.events
#
#spring.cloud.stream.rabbit.default.producer.exchange-type=topic
#spring.cloud.stream.rabbit.default.producer.routingKeyExpression=headers['eventType']

#kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.cloud.stream.bindings.handleMatch-in-0.group=matching-engine-queue
spring.cloud.stream.kafka.binder.autoAddPartitions=true
spring.cloud.stream.bindings.handleMatch-out-0.destination=
spring.cloud.stream.bindings.handleMatch-out-0.content-type=application/json
spring.cloud.stream.kafka.bindings.handleMatch-in-0.consumer.startOffset=latest
spring.cloud.stream.kafka.bindings.handleMatch-in-0.consumer.resetOffsets=true