spring.application.name=matching-service
server.port=8083
spring.profiles.active=reactive

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

spring.cloud.function.definition=handleMatch

spring.cloud.stream.bindings.handleMatch-in-0.destination=orchestration.orders.created
spring.cloud.stream.bindings.handleMatch-in-0.group=matching-engine-queue
#gambiarra para n criar exchange handleMatch-out-0
spring.cloud.stream.bindings.handleMatch-out-0.destination=

#kafka
#spring.kafka.bootstrap-servers=localhost:9092
#spring.cloud.stream.bindings.handleMatch-in-0.group=matching-engine-queue
#spring.cloud.stream.kafka.binder.autoAddPartitions=true
#spring.cloud.stream.bindings.handleMatch-in-0.destination=order.events
#spring.cloud.stream.bindings.handleMatch-out-0.destination=trade.events
#spring.cloud.stream.bindings.handleMatch-out-0.content-type=application/json
#spring.cloud.stream.kafka.bindings.handleMatch-in-0.consumer.startOffset=latest
#spring.cloud.stream.kafka.bindings.handleMatch-in-0.consumer.resetOffsets=true